### ISSUE TITLE
Not running via conda on macOS

### ISSUE THREAD

**Issue by acesnik** [CSBiology/ProteomIQon#16]
**Describe the bug**
Application installed via conda doesn't run on macOS. It looks like the `meta.yaml` is using `dotnet install`, but I think this means that it is built in the `noarch` container, i.e. Linux, and it can't be run in macOS. In any case, it's not working on my side.

It looks like the F# `.fsproj` files also reference net5.0; it might be that .NET 5.0 should be pinned like this:
```
requirements:
  host:
    - dotnet-sdk =5.0
  run:
    - dotnet-runtime =5.0
```

**To Reproduce**

On macOS:
1. `conda install -c bioconda proteomiqon-peptidedb`
2. `proteomiqon-peptidedb --help`
 
**Expected behavior**
Help menu...

**Screenshots**
These happen with both .NET 5.0 and 6.0 runtimes
<img width="899" alt="image" src="https://user-images.githubusercontent.com/16342951/161665752-fc6e15f5-1d0a-4f06-be7d-8d0bce57c40f.png">
<img width="899" alt="image" src="https://user-images.githubusercontent.com/16342951/161665803-0daabe51-310f-4591-92f7-22073db7fb06.png">

**OS and framework information (please complete the following information):**
 - OS: macOS
 - OS Version:  10.15.7 on x86_64
 - .Net core SDK version: 6.0.2

**Comment by ZimmerA** [comment]
Thank you for submitting this!
When we released the last conda package for the ProteomIQon, the dotnet package was not available on MacOS.  I assume it has something to do with that. It looks like you did some work to change this tough, so we will definitely get this to work on macOS!
Unfortunately, I currently do not have a Mac set up to play around with this. I might hook up my old Mac mini and see how far I can get with that (that thing is painfully slow)!

**Comment by acesnik** [comment]
No problem! Yeah, I've been working a bit on `dotnet` on the conda-forge side to get it working for macOS and such! 😄 

In case it's helpful, here's an example of a bioconda package using `dotnet` that's running for me on both macOS and linux: https://github.com/bioconda/bioconda-recipes/tree/master/recipes/flashlfq. It puts an executable shim (FlashLFQ.sh) into the `bin/` folder instead of using `dotnet install`.

**Comment by ZimmerA** [comment]
Hey @acesnik can you check if https://anaconda.org/bioconda/proteomiqon-mzmltomzlite is working for you on mac? 
We changed the recipe according to the flashlfq example you provided. 

During the process of changing the build I noticed that the dotnet sdk's do not work properly (atleasts on bioconda). When executing commands like dotnet tool install or dotnet restore the tool segfaults after printing the welcome message. That might also be the reason the packages were not working for you on mac. They could not be built anymore.

**Comment by acesnik** [comment]
It's executing! Just downloaded it from `bioconda` and was able to get the help menu on my mac.

Good to know, regarding dotnet-sdk segfaulting. Could you open an issue here with that, so we can remember to investigate it? https://github.com/conda-forge/dotnet-feedstock

**Comment by ZimmerA** [comment]
Awesome, will do! Thanks!
